site_name: Valo-Api Docs

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
      
extra:
  generator: false
      
theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: red
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - API Reference:
    - Overview: api-reference/overview.md
    - Endpoints:
      - Rank Related: api-reference/rank.md
      - Stats Related: api-reference/stats.md
      - Record Related: api-reference/record.md